### ISSUE TITLE
Adding GitHub topics to repositories

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/maintainer-RFCs#5]
Back in January 2017, GitHub [introduced](https://github.blog/2017-01-31-introducing-topics/) GitHub topics. They allow for repository discoverability across GitHub. Additionally, as the number of lessons within The Carpentries has grown, we have been looking at programmatic ways to identify which repositories within our organizations are lessons (as opposed to tools, templates, etc.) GitHub topics allow us to do this through the GitHub API.

Some of our repositories are already using them, however, we are looking to standardize GitHub topics across our lesson programs.

The Lesson Infrastructure committee (@carpentries/lesson-infrastructure-committee), following a proposal put together by community member Robert Zinna (@Zinnar), had approved a tentative plan for Topics for our repositories https://github.com/carpentries/lesson-infrastructure/issues/8

Now that we have this repository for RFCs, we are sharing [an initial draft](https://docs.google.com/spreadsheets/d/1ftV5L2C01aeHrMTWG0WWVm3MSeHMFZOEKw2a7ing138/edit?usp=sharing) (as a Google Spreadsheet) of the different GitHub Topics that would be added to our repositories.

The spreadsheet is organized as follows:
- `repository_url`: URL of the GitHub repository
- `repository`: name of the repository
- `topics_carpentries`: all repositories would get a `carpentries` topic
- `topics_lesson_program`: the lesson program for the repository
- `topics_repo_type`: type of repository: `lesson`, `template`, `infrastructure`, etc.
- `topics_tool`: the tool taught by the lesson
- `topics_curriculum`: the curriculum the lesson belongs to
- `topics_skills`: the skills taught in the lesson (several skills are listed for each, they will become independant topics)
- `topics_language`: the human language for the lesson
- `topics_life_cyle`: the life cycle for the lesson

We are requesting feedback and input from Maintainers on these proposed GitHub Topics. You can leave a comment on the Google Spreadsheet, a comment on this GitHub issue, or send us an email at team@carpentries.org.

## Timeline

Please comment on this proposal by [Friday, 25 October midnight UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20191025T00). @fmichonneau, @ErinBecker, and members of the @carpentries/lesson-infrastructure-committee will respond here to answer questions and summarise potential paths forward.

**Comment by dvanic** [comment]
I'm not sure whether to tag cloud genomics with shell as a skill we teach, as it is what we use but not necessarily explicitly teach per se...

**Comment by remram44** [comment]
The '[workshop](https://github.com/topics/workshop)' and '[workshop-website](https://github.com/topics/workshop-website)' topics already exist, I recommend using one of those rather than '[workshop-overview](https://github.com/topics/workshop-overview)' which is not currently used anywhere on the site. It's a bit too descriptive and too specific to the Carpentries' workflow, let's pick something that makes sense in the wider GitHub community.

Similarly, '[spreadsheet](https://github.com/topics/spreadsheet)' is more popular than '[spreadsheets](https://github.com/topics/spreadsheets)'; '[image-processing](https://github.com/topics/image-processing)' (or '[computer-vision](https://github.com/topics/computer-vision)') is more popular than '[image-analysis](https://github.com/topics/image-analysis)' (and have official descriptions). '[data-management](https://github.com/topics/data-management)' is also a widely used term (in academia/libraries) while '[data-organization](https://github.com/topics/data-organization)' is only used by 1 repository.

'[webscraping](https://github.com/topics/webscraping)' has alternatives '[scraping](https://github.com/topics/scraping)' (most popular) and '[web-scraping](https://github.com/topics/web-scraping)' (my preferred spelling but less widely used), I'm not sure what should be used. Similarly, '[versioning](https://github.com/topics/versioning)' is more popular than '[version-control](https://github.com/topics/version-control)' (though 'version-control' is my preferred spelling too).

**Comment by fmichonneau** [comment]
@remram44 thanks for checking the popularity of the different tags. It's going to be useful to figure out which one to choose.

**Comment by fmichonneau** [comment]
the RFC has been edited and the period for comments has been set to last until Friday, 25 October at midnight (UTC).

**Comment by remram44** [comment]
> the RFC has been edited

What are the changes? Google Docs doesn't let people without edit access view the history :slightly_frowning_face:

**Comment by ErinBecker** [comment]
@remram44 - The changes that @fmichonneau is talking about are to the GH issue, not to the Google Doc. He updated the "Timeline" to add a comment-by date.

**Comment by ErinBecker** [comment]
@dvanic - that's a good question! The same question applies to other lessons that use one technology to teach another (e.g. Git lesson uses shell). Any suggestions from @swcarpenty/git-novice-maintainers, @swcarpentry/git-novice-es-maintainers? 

Edit: Looks like I can't tag teams from other GH organizations. ☹️

**Comment by maxim-belkin** [comment]
On behalf of the maintainers of `python-novice-inflammation` lesson: we'll discuss which "topics_skills" we think are appropriate and get back to you.. ETA: a few days.

**Comment by ErinBecker** [comment]
Summary of discussion at 1st Maintainer meeting today:

- When possible, use the more popular topics to help with discoverability
- We will have a `carpentries` tag to help people filter to just our lessons, as well as lesson program specific tags.
- Using a hyphen (`software-carpentry`) or a space (`software carpentry`) in a topic name gives the same results, but having things as a single word (`softwarecarpentry`) doesn't.

**Comment by ErinBecker** [comment]
Thank you everyone for your feedback on this conversation! @fmichonneau and I will be meeting tomorrow to discuss this feedback and plan a timeline for implementing topics across all of The Carpentries repos.

**Comment by ErinBecker** [comment]
Based on feedback, I've updated [the Google Sheet](https://docs.google.com/spreadsheets/d/1ftV5L2C01aeHrMTWG0WWVm3MSeHMFZOEKw2a7ing138/edit#gid=0). In cases where there were alternatives for the proposed tags, I included multiple alternatives when they were *similar* in frequency of usage, and included only the more popular topic when it was at least *an order of magnitude* more frequent. Since we're not limited in the number of topics on a repo, and our primary goal for using this feature is to enhance discoverability, I lean towards using more tags where there is evidence that the community is using both tags.

Summary of changes: 
- `workshop-overview` (0) --> `workshop` (1816) (`workshop-website` has only 28 repos)
- `spreadsheets` --> both `spreadsheets` (103) and `spreadsheet` (489)
- `image-analysis`(444)  --> `image-processing` (6102) and `computer-vision` (7221)
- `data-organization` (1) --> `data-management` (241)
- `webscraping`  --> `webscraping` (1394), `scraping` (1502), and `web-scraping` (1093)
- `version-control` --> both `version-control` (402) and `versioning` (546)
- `data-visualisation` --> `data-visualisation` (204), `data-visualization` (5003) (in this case, I'm including both spelling options so repo will be discoverable by folks who use both sets of English spelling conventions)
- `publication` --> `publication` (145) and `publishing` (434)
- `regular-expressions` --> `regular-expressions` (302) and `regex` (1603)

**Comment by maxim-belkin** [comment]
For SWC/Python-novice-inflammation lesson, could you please add the following topics?

programming
data-analysis
data-visualization
automation
functions
loops
matplotlib
numpy

**Comment by fmichonneau** [comment]
the topics have been added to the lessons.

**Comment by remram44** [comment]
Did GitHub remove the pagination from the topic pages? I see 8 repos on each topic page with no way to browse more?
